---
version: '2.1'

services:
  cci: &defaults
    image: jumanjiman/cci
    build:
      context: src/
      args:
        - BUILD_DATE
        - TAG
        - VCS_REF
        - CI_BUILD_URL=${CIRCLE_BUILD_URL}
      labels:
        io.github.jumanjiman.ci-build-url: ${CI_BUILD_URL}
        io.github.jumanjiman.version: ${TAG}
        io.github.jumanjiman.build-date: ${BUILD_DATE}
        io.github.jumanjiman.vcs-ref: ${VCS_REF}
        io.github.jumanjiman.license: MIT
        io.github.jumanjiman.docker.dockerfile: src/Dockerfile
        io.github.jumanjiman.vcs-type: Git
        io.github.jumanjiman.vcs-url: https://github.com/jumanjihouse/cci.git

  ci:
    <<: *defaults
    entrypoint: goss
    command: -g /goss.yaml validate --format=tap
    environment:
      - BUILD_DATE
      - TAG
      - VCS_REF
      - CI_BUILD_URL
    read_only: true
    cap_drop:
      - all
    cpu_shares: 1023
    mem_limit: 1G
    shm_size: 32M
    stdin_open: true
    tty: true
