---
version: '2.1'

services:
  cci: &defaults
    image: jumanjiman/cci
    build:
      context: src/
      args:
        - BUILD_DATE
        - TAG
        - VCS_REF
        - CI_BUILD_URL=${CIRCLE_BUILD_URL}
    read_only: true
    cap_drop:
      - all
    cpu_shares: 1023
    mem_limit: 1G
    shm_size: 32M
    stdin_open: true
    tty: true

  ci:
    <<: *defaults
    entrypoint: goss
    command: -g /goss.yaml validate --format=tap
