---
# https://circleci.com/docs/docker
version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:202004-01

    working_directory: ~/cci/

    steps:
      - checkout

      - run:
          name: Bootstrap the devenv
          command: |
            ci/bootstrap

      - run:
          name: Build the image
          command: |
            ci/build

      - run:
          name: Test the image
          command: |
            ci/test

      - deploy:
          name: Deploy from master branch
          # yamllint disable rule:line-length
          command: |
            if [[ ${CIRCLE_BRANCH} = master ]] && [[ -z ${CIRCLE_PR_NUMBER} ]]; then
              ci/publish
            fi
