#!/bin/bash
set -eEu
set -o pipefail

main() {
  setup_pyenv
  setup_python_path
  install_pips
  pre-commit install-hooks
  mkbin
  install_shellcheck
  install_shfmt
  add_upstream_git_remote
  fetch_upstream
}

setup_pyenv() {
  if ! command -v pyenv &>/dev/null; then
    return
  fi

  py3="3.6.3"
  if ! pyenv versions | grep "${py3}" &>/dev/null; then
    pyenv install "${py3}"
  fi
  pyenv global "${py3}"

  # Avoid error or CircleCI:
  # NameError: name 'platform_system' is not defined
  pip3 install --upgrade pip setuptools
}

setup_python_path() {
  PYTHON_PATH="$(python3 -c "import site; print(site.USER_BASE)")"
  readonly PYTHON_PATH

  if ! grep "${PYTHON_PATH}/bin" <(printenv PATH) &>/dev/null; then
    export PATH="${PATH}:${PYTHON_PATH}/bin"
  fi
}

install_pips() {
  pip3 install \
    --compile \
    --disable-pip-version-check \
    --no-cache-dir \
    --quiet \
    --user \
    --verbose \
    -r ci/requirements.txt
}

mkbin() {
  mkdir -p ~/bin || :
  if ! grep -E ':~/bin[:$]' <<<"$(printenv PATH)" &>/dev/null; then
    export PATH="${PATH}:~/bin"
  fi
}

install_shellcheck() {
  if ! command -v shellcheck &>/dev/null; then
    # Install latest statically-linked version of
    # https://github.com/koalaman/shellcheck
    local -r version="latest"
    local -r tarball="shellcheck-${version}.linux.x86_64.tar.xz"
    local -r url="https://github.com/koalaman/shellcheck/releases/download/${version}"

    pushd /tmp
    curl -L -ssL -O "${url}/${tarball}"
    tar xvJf ${tarball}
    popd
    cp /tmp/shellcheck-latest/shellcheck ~/bin/
    rm -fr /tmp/shellcheck*
  fi
}

install_shfmt() {
  if ! command -v shfmt &>/dev/null; then
    # Install statically-linked version of shfmt from
    # https://github.com/mvdan/sh
    local -r SHFMT_VERSION="v3.0.1"
    curl -L -ssL -o ~/bin/shfmt \
      "https://github.com/mvdan/sh/releases/download/${SHFMT_VERSION}/shfmt_${SHFMT_VERSION}_linux_amd64"
    chmod 0755 ~/bin/shfmt
  fi
}

add_upstream_git_remote() {
  if ! git remote show upstream &>/dev/null; then
    git remote add upstream https://github.com/jumanjihouse/cci.git
  fi
}

fetch_upstream() {
  git fetch upstream
}

main
