#!/bin/bash
set -e

docker rm mb &> /dev/null || :
docker-compose -f docker-compose-mb.yaml build
docker create --name mb mb true
docker cp mb:/tmp/microbadger src/

docker-compose build
echo
echo
docker images | egrep 'jumanjiman/cci\b'
