#!/bin/bash
set -eEu
set -o pipefail

cat >ci/vars <<EOF
export BUILD_DATE=$(date +%Y%m%dT%H%M)
export VCS_REF=$(git describe --abbrev=7 --tags --always)
export TAG=$(date +%Y%m%d.%H%M)
EOF

. ci/vars

echo
echo Remove mb container if it has been created.
docker rm mb &>/dev/null || :

echo
echo Build mb image.
docker-compose -f docker-compose-mb.yaml build

echo
echo Copy microbadger utility.
docker create --name mb mb true
docker cp mb:/tmp/microbadger src/

echo
echo Build cci image.
docker-compose build

echo
echo Show images.
docker images | grep -E 'jumanjiman/cci\b'
