#!/bin/bash
set -eEu
set -o pipefail

. ci/vars

# shellcheck disable=SC2154
docker login -u "${user}" -p "${pass}"
docker tag jumanjiman/cci "jumanjiman/cci:${TAG}"
docker push "jumanjiman/cci:${TAG}"
docker push jumanjiman/cci:latest
docker logout
