#!/bin/bash
set -eEu
set -o pipefail

. ci/bootstrap
. ci/vars

main() {
  run_ci
  run_precommit
}

run_ci() {
  echo
  echo Run CI tests.
  docker-compose run ci
}

run_precommit() {
  echo
  echo Run various file checks.

  # http://pre-commit.com/#pre-commit-run
  readonly DEFAULT_PRECOMMIT_OPTS="--all-files --hook-stage manual"

  # Allow user to override our defaults by setting an env var.
  readonly PRECOMMIT_OPTS="${PRECOMMIT_OPTS:-$DEFAULT_PRECOMMIT_OPTS}"

  # shellcheck disable=SC2086
  /usr/bin/time pre-commit run ${PRECOMMIT_OPTS}
}

main
