---
# This file configures https://pre-commit.com/
# to use specific hooks and options.

fail_fast: false

repos:
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.0.2
    hooks:
      - id: check-mailmap
      - id: fasterer
      - id: forbid-binary
      - id: git-check  # Configure in .gitattributes
      - id: git-dirty  # Configure in .gitignore
      - id: markdownlint
      - id: reek
      - id: require-ascii
      - id: rubocop
      - id: script-must-have-extension
      - id: script-must-not-have-extension
      - id: shellcheck
      - id: shfmt

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.23.0
    hooks:
      - id: yamllint
        args: [--format, parsable, --strict]

  - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    rev: 0.0.10
    hooks:
      - id: yamlfmt
        args: [--mapping, '2', --sequence, '4', --offset, '2', --width, '150']
        exclude: src/goss.yaml  # This file uses go template

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.0.1
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-symlinks
      - id: check-vcs-permalinks
      - id: detect-private-key

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.1
    hooks:
      - id: flake8

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.7
    hooks:
      - id: forbid-crlf
      - id: forbid-tabs
        exclude: >
          (?x)^(
            Makefile|
            .*\.go
          )$

  - repo: https://github.com/chriskuehl/puppet-pre-commit-hooks.git
    rev: v2.1.0
    hooks:
      - id: puppet-validate
      - id: erb-validate
      - id: epp-validate
      - id: puppet-lint
        args:
          - --fail-on-warnings
          - --no-documentation-check

  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.13.1
    hooks:
      - id: gitlint
        stages: [commit-msg]

      - id: gitlint
        entry: gitlint --commits upstream/master..
        exclude: .*
        always_run: true
        stages: [manual]
