#!/bin/bash
set -eEu
set -o pipefail

################################################################################
# Run "ci/bootstrap" to install dependencies for the test harness.
################################################################################

trap finish EXIT

export TIME='
%C
Elapsed wall clock time:    %E
CPU seconds in kernel mode: %S
CPU seconds in user mode:   %S
Max RSS in KiB:             %M
'

finish() {
  declare -ri RC=$?
  if [[ ${RC} -eq 0 ]]; then
    echo "$0 OK" >&2
  else
    echo "[ERROR] $0" >&2
  fi
}

echo '---> pre-commit'
# Install hook environments now. Otherwise, they get
# installed when first invoked, and the time to install
# artificially skews the time reported for the test run.
/usr/bin/time pre-commit install-hooks
