FROM alpine:3.9

RUN apk add --no-cache \
      git \
      go \
      && \
    :

COPY microbadger.go /microbadger/

ENV GOPATH=/tmp/ \
    CGO_ENABLED=0 \
    GOOS=linux \
    LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:$LIBRARY_PATH

RUN cd /microbadger/ && \
    go get -d ./... && \
    go build \
      -o /tmp/microbadger \
      -a \
      -tags netgo \
      -ldflags '-extldflags "-static" -s' \
      -buildmode exe \
      microbadger.go
